### ISSUE TITLE
Incorrect Power Conversion in P1812.py Line 429

### ISSUE THREAD

**Issue by drcaguiar** [eeveetza/Py1812#4]
I've noticed a potential issue in the P1812.py script, specifically at line 429 where the transmitter power (Ptx) is being converted for the EpPtx calculation:

`EpPtx = Ep + 10 * np.log10(Ptx)`

Given that Ptx is provided in kilowatts (kW), converting to dBm should first involve transforming Ptx to milliwatts (mW), as dBm is a power ratio in decibels relative to 1 mW.

Therefore, the correct formula should be:

`EpPtx = Ep + 10 * np.log10(Ptx * 1e6)`

**Comment by eeveetza** [comment]
Note that equation (70) already has the factor $199.36$ dB that takes into account that the effective radiated power amounts to 1 kW:

<img width="1119" alt="image" src="https://github.com/eeveetza/Py1812/assets/74705280/172b6384-d66a-41b3-90b5-b2a5b7aa67b5">

For any other effective radiated power, $P_{\mathrm{Tx}}$, expressed in kW, the conversion factor will be: 
$E_p(P_{\mathrm{Tx}}) = E_p(1\mathrm{kW}) + 10\log_{10}(P_{\mathrm{Tx}}/1\mathrm{ kW})$

This is correctly implemented in the code in line 429.

With this explanation, the issue is closed.
